### PR TITLE
Xcode11.3 swift5.0

### PR DESCRIPTION
**Pull request by hemmlj**
Used Conversion Assistent to migrate to macOS Catalina 10.15.3, Xcode11.3, Swift 5.0, MacPorts installed for FFmpeg 4.1 rebuild with rebuild done. nice project to go further. testing while coding :)

### CODE REVIEW

**Comment by hemmlj** [comment]
Hi, I created this branch to convert source-code to Swift 5.0, using Xcode 11.3 on macOS Catalina 10.15.3, using the assistant and learning to code in swift. (starter). I managed to get rid of warnings and as a latest step I included FFmpeg 4.2.2 just for learning reasons. This is a great project to work on. I enjoy listening to music while coding and testing. Nice work.

**Comment by maculateConception** [comment]
Hi hemmlj,

Thanks for your interest in Aural Player ! And I see you've been busy with it.

I'm not sure how to do pull requests, and I've never collaborated with anyone directly on GitHub before.

For now, can you continue your work on your personal branch, and then maybe someday, we can look at doing a merge.

Are you planning to add new features ? Or was this mostly to upgrade to Swift 5 ?

Best regards,
MC

**Comment by maculateConception** [comment]
> 
> 
> Hi, I created this branch to convert source-code to Swift 5.0, using Xcode 11.3 on macOS Catalina 10.15.3, using the assistant and learning to code in swift. (starter). I managed to get rid of warnings and as a latest step I included FFmpeg 4.2.2 just for learning reasons. This is a great project to work on. I enjoy listening to music while coding and testing. Nice work.

Ah ok, that's great. I'm glad if it helps you with your learning process !

Cheers :)

**Comment by hemmlj** [comment]
Hi MC, for now I am just playing around with git, GitHub, Xcode and swift to get familiar with all the tools. There are currently no plans on my site to extend your nice music-player - but we will see. First I have to understand the model and where things are "living". - Last update was regarding switch with Catalina 10.15.4 to Xcode 11.4 and Swift 5.1 (or 5.2) - I think I could fix the merging issues with my branch as I have uploaded binary files and lock-files with some updates. Sorry for that. Have a nice time and thanks for your time you have already spent on this great work. Bye, stay healthy, Hemmlj (Joerg)

**Comment by maculateConception** [comment]
Hi Joerg, that sounds great. Yes, this is a nice project for you to learn Swift. However, I just want to point out a few things so that you are not misled by my code.

This is my first Swift project ever. I was a Java programmer for many years, and just tried developing a music player because I wanted something simple to use on Mac.

Also, I do not follow Apple's standard guidelines for Cocoa app development or the official Swift language recommendations. I just program with the previous knowledge I have from other previous projects I have worked on.

So, my point is - my code will be good for you to learn from, but keep in mind that the exact style in which I have written the code, and how the project is organized, is not following the general best practices from Apple and Swift. Mine is just an enthusiast project and I don't care about following the guidelines. I'm doing this for fun, mostly.

If you ever have any questions about the project structure, I will be happy to give you a few tips or pointers, perhaps to explain code structure so that you may have an easier time figuring it out.

Just let me know if you need anything. Thanks !

**Comment by hemmlj** [comment]
Hi maculateConception, thank you for your little "Warnings" on your coding style. :) I will take them into my considerations when reading it. I will come back here once I have proposals for additional features (don't expect this to be soon). I am looking forward to your migration to Swift 5. Meanwhile have a good time and thank you for your time! Regards, Joerg - btw, I was once a visual basic and vba coder (a long time ms access) and have started learning to code with Cobol, Pascal and Fortran at school. These programming languages were lacking of GUI Interfaces mostly.

**Pull request closed without merging**
