### PR TITLE
WIP: M1 support

### PR DESCRIPTION
**Pull request by termdew**
Hi there 🙂 

I managed to get Aural Player working on my M1 MacBook Air.
I created a branch in my repository fork and added universal dylibs for x64 and arm64 for it.

As I don't have any x64 Mac machine to test it, please do so.

Looking forward to your feedback 🙂

### CODE REVIEW

**Comment by maculateConception** [comment]
Hi @termdew,

Thank you so much for your interest in the project and for compiling universal dylibs (and for confirming that it works on M1 hardware). I really appreciate your work, esp. because I don't have access to M1 hardware.

One comment - in your screenshot, I noticed that the playlist table view has a border. Are you able to get the table view working properly without the border ? In my own development, I struggled to get it working (alignment) without adding a border, so it is interesting that you have probably run into the same problem.

I have been away from the project for a while, so it may take me a while to get back into it and review your work. But I will try my best to review it and incorporate your changes if everything checks out. At the very least, the universal ffmpeg binaries will be of great help. The playlist view problem is the other outstanding problem (text alignment).

Thanks again,
maculateConception

**Comment by maculateConception** [comment]
By the way, your screenshot contains your Mac's serial number. You might want to erase it and re-post the image :)

**Comment by maculateConception** [comment]
Hi, can you please share the build / configuration script you used to build the universal ffmpeg dylibs ? I need this because the script to build ffmpeg is a part of the repository, so that anyone wanting to reproduce the build can easily do so in the future. Please see [/Resources/ffmpeg/build_ffmpeg.sh](https://github.com/maculateConception/aural-player/blob/master/Resources/ffmpeg/build-ffmpeg.sh). This is why I asked you a question in my first response above ^.

You can provide the script by modifying the **/Resources/ffmpeg/build_ffmpeg.sh** script in your fork with the script you used to build ffmpeg.

Also, which version of ffmpeg source did you use for the build ? Is it the one from /Resources/ffmpeg ?

Without this, I cannot approve the pull request. Thanks.

**Comment by termdew** [comment]
Hi and sorry that I didn't respond on your question,

I didn't use the ffmpeg build script. I built arm64 dylibs for ffmpeg myself and then I created universal dylibs with an executable called "lipo".

The command looked like this: 
```
lipo development/ffmpeg-4.4/libavutil/libavutil.56.dylib /Users/termdew/development/aural-player/Frameworks/libavutil.56.dylib -output /Users/termdew/development/aural-player/Frameworks/libavutil.56.dylib -create
```

It takes both the arm64 and x64 dylib and packs it in to one.
I think it should work if you ship the universal dylibs from my pull request. But I will also test your build script on my M1 machine. 🙂

**Comment by maculateConception** [comment]
> I built arm64 dylibs for ffmpeg from source (version 4.4) myself

Can you share the exact compile command you used to build for arm64 ? Including all the --configure params. This is the most important thing.

See, I need a script that can do all this in one long step. So, I will take your arm64 steps and incorporate them into my existing build script.

Thanks.

**Comment by maculateConception** [comment]
I have figured out how to cross-compile for arm64 on my x64 machine, and I have modified the ffmpeg build script accordingly. Please see [this changelist](https://github.com/maculateConception/aural-player/commit/1c6dfe5644e5b491f7036121b690c5de8fe37f73).

By the way, your dylibs are not universal, they are only for arm64. I checked them with lipo. So, I cannot use them. In any case, as I mentioned, dylibs for Aural Player need to be built and configured a certain way (referring to the build script), so I would not have been able to use your dylibs even if they worked on my machine. That is why I asked you for your build instructions.

I am now closing this request, as I was able to independently build universal ffmpeg binaries, so this request is no longer relevant.

**Comment by maculateConception** [comment]
[Version 3.0.0] released, with proper M1 support ... in case you are interested in trying it out :)

**Pull request closed without merging**
